<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>plantorv_planner</name>
  <version>1.0.0</version>
  <description>Plans and executes the known manipulation actions of PLANTORV on a UR3</description>
  <maintainer email="enrico.saccon@unitn.it">Enrico Saccon</maintainer>
  <license>Apache 2.0</license>

  <depend>plantorv_interfaces</depend>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>builtin_interfaces</depend>
  <depend>controller_manager_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>gripper_interfaces</depend>

  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>cartesian_motion_controller</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
