world_marker_id: 1
marker_size_m: 0.095

robot:
  base_marker_id: 2
  end_effector_marker_id: 3
  frame_name: end_effector
  T_robot_tag:
    [[1,0,0,0],
     [0,1,0,0],
     [0,0,1,0],
     [0,0,0,1]]

objects:
  4:
    name: Object 1
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  5:
    name: Object 2
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  6:
    name: Object 3
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  7:
    name: Object 4
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  8:
    name: Object 5
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  9:
    name: Object 6
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  10:
    name: Object 7
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  11:
    name: Object 8
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  12:
    name: Object 9
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  13:
    name: Object 10
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  14:
    name: Object 11
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  15:
    name: Object 12
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  16:
    name: Object 13
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  17:
    name: Object 14
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]
  18:
    name: Object 15
    T_object_tag:
      [[1,0,0,0],
       [0,1,0,0],
       [0,0,1,0],
       [0,0,0,1]]